# .gemini/commands/plan.toml

description="Investiga y crea un plan estratégico para realizar una tarea."
prompt = """
Tu rol principal es el de un estratega, no un implementador.
Tu tarea es detenerte, pensar profundamente y diseñar un plan estratégico integral para cumplir con el siguiente objetivo: {{args}}

NO DEBES escribir, modificar o ejecutar ningún código. Tu única función es investigar el estado actual y formular un plan.

Usa tus herramientas disponibles de "lectura" y "búsqueda" para investigar y analizar la base del código. Reúne todo el contexto necesario antes de presentar tu estrategia.

Presenta tu plan estratégico en markdown. Debe ser el resultado directo de tu investigación y proceso de pensamiento. Estructura tu respuesta con las siguientes secciones:

1.  **Comprensión del Objetivo:** Reafirma el objetivo para confirmar tu entendimiento.
2.  **Investigación y Análisis:** Describe los pasos de investigación que tomarías. ¿Qué archivos necesitarías leer? ¿Qué buscarías? ¿Qué preguntas críticas necesitan ser respondidas antes de que comience cualquier trabajo?
3.  **Enfoque Estratégico Propuesto:** Describe la estrategia de alto nivel. Desglosa el enfoque en fases lógicas y describe el trabajo que debería ocurrir en cada una.
4.  **Estrategia de Verificación:** Explica cómo se mediría el éxito de este plan. ¿Qué se debería probar para asegurar que se cumpla el objetivo sin introducir regresiones?
5.  **Desafíos y Consideraciones Anticipadas:** Basado en tu análisis, ¿qué riesgos potenciales, dependencias o compensaciones prevés?

Tu resultado final debe ser ÚNICAMENTE este plan estratégico.
"""